import type {
  Workout,
  ProgressData,
  Achievement,
} from '@/lib/types';
import {
  Award,
  Calendar,
  Flame,
  Zap,
  Star,
  Trophy,
  Activity,
  HeartPulse,
  CalendarCheck,
  Medal,
  MessageSquare,
} from 'lucide-react';
import { getImageData } from './placeholder-images';

export const workouts: Workout[] = [
  {
    slug: 'full-body-blast',
    title: 'Full Body Blast',
    category: 'Strength',
    duration: 30,
    calories: 300,
    intensity: 'Intermediate',
    equipment: ['Dumbbells', 'Bench'],
    description: 'A comprehensive full-body workout to build strength and muscle.',
    image: getImageData('strength-workout'),
    steps: [
      { instruction: 'Warm-up: 5 minutes of light cardio', duration: 300, animationUrl: getImageData('generic-animation') },
      { instruction: 'Dumbbell Squats: 3 sets of 12 reps', duration: 180, animationUrl: getImageData('squat-animation') },
      { instruction: 'Push-ups: 3 sets to failure', duration: 120, animationUrl: getImageData('pushup-animation') },
      { instruction: 'Bent-over Rows: 3 sets of 10 reps', duration: 180, animationUrl: getImageData('generic-animation') },
      { instruction: 'Plank: 3 sets, hold for 60 seconds', duration: 180, animationUrl: getImageData('plank-animation') },
      { instruction: 'Cool-down: 5 minutes of stretching', duration: 300, animationUrl: getImageData('stretching-workout') },
    ],
    translations: {
      es: {
        title: 'Explosión de Cuerpo Completo',
        description: 'Un entrenamiento completo para todo el cuerpo para desarrollar fuerza y músculo.',
        steps: [
          { instruction: 'Calentamiento: 5 minutos de cardio ligero' },
          { instruction: 'Sentadillas con mancuernas: 3 series de 12 repeticiones' },
          { instruction: 'Flexiones: 3 series hasta el fallo' },
          { instruction: 'Remo inclinado: 3 series de 10 repeticiones' },
          { instruction: 'Plancha: 3 series, mantener durante 60 segundos' },
          { instruction: 'Enfriamiento: 5 minutos de estiramiento' },
        ],
      }
    }
  },
  {
    slug: 'cardio-core-crusher',
    title: 'Cardio Core Crusher',
    category: 'Cardio',
    duration: 20,
    calories: 250,
    intensity: 'Beginner',
    equipment: ['None'],
    description: 'A quick and effective cardio session to get your heart rate up.',
    image: getImageData('cardio-workout'),
    steps: [
        { instruction: 'Jumping Jacks: 60 seconds', duration: 60, animationUrl: getImageData('jumpingjack-animation') },
        { instruction: 'High Knees: 60 seconds', duration: 60, animationUrl: getImageData('cardio-animation') },
        { instruction: 'Burpees: 30 seconds', duration: 30, animationUrl: getImageData('burpee-animation') },
        { instruction: 'Rest: 30 seconds', duration: 30, animationUrl: getImageData('generic-animation') },
        { instruction: 'Repeat circuit 3 times', duration: 600, animationUrl: getImageData('generic-animation') },
        { instruction: 'Cool-down: 5 minutes of light stretching', duration: 300, animationUrl: getImageData('stretching-workout') },
    ],
  },
  {
    slug: 'morning-yoga-flow',
    title: 'Morning Yoga Flow',
    category: 'Yoga',
    duration: 15,
    calories: 100,
    intensity: 'Beginner',
    equipment: ['Yoga Mat'],
    description: 'Start your day with a gentle and energizing yoga flow.',
    image: getImageData('yoga-workout'),
    steps: [
        { instruction: 'Child\'s Pose: 60 seconds', duration: 60, animationUrl: getImageData('yoga-animation') },
        { instruction: 'Cat-Cow Stretch: 5 rounds', duration: 120, animationUrl: getImageData('yoga-animation') },
        { instruction: 'Downward-Facing Dog: 60 seconds', duration: 60, animationUrl: getImageData('yoga-animation') },
        { instruction: 'Sun Salutation A: 3 rounds', duration: 300, animationUrl: getImageData('yoga-animation') },
        { instruction: 'Savasana: 3 minutes', duration: 180, animationUrl: getImageData('yoga-animation') },
    ],
  },
  {
    slug: 'hiit-power-session',
    title: 'HIIT Power Session',
    category: 'HIIT',
    duration: 25,
    calories: 400,
    intensity: 'Advanced',
    equipment: ['None'],
    description: 'High-intensity interval training to maximize calorie burn.',
    image: getImageData('hiit-workout'),
    steps: [
        { instruction: 'Warm-up: 3 minutes', duration: 180, animationUrl: getImageData('generic-animation') },
        { instruction: 'Sprint in place: 30 seconds', duration: 30, animationUrl: getImageData('cardio-animation') },
        { instruction: 'Rest: 15 seconds', duration: 15, animationUrl: getImageData('generic-animation') },
        { instruction: 'Jump Squats: 30 seconds', duration: 30, animationUrl: getImageData('squat-animation') },
        { instruction: 'Rest: 15 seconds', duration: 15, animationUrl: getImageData('generic-animation') },
        { instruction: 'Repeat circuit 8 times', duration: 900, animationUrl: getImageData('generic-animation') },
        { instruction: 'Cool-down: 5 minutes', duration: 300, animationUrl: getImageData('stretching-workout') },
    ],
  },
  {
    slug: 'evening-stretch',
    title: 'Evening Stretch',
    category: 'Stretching',
    duration: 10,
    calories: 50,
    intensity: 'Beginner',
    equipment: ['None'],
    description: 'Relax and unwind with a full-body stretching routine.',
    image: getImageData('stretching-workout'),
    steps: [
        { instruction: 'Neck Rolls: 30 seconds each side', duration: 60, animationUrl: getImageData('generic-animation') },
        { instruction: 'Shoulder Stretch: 30 seconds each arm', duration: 60, animationUrl: getImageData('generic-animation') },
        { instruction: 'Hamstring Stretch: 60 seconds each leg', duration: 120, animationUrl: getImageData('generic-animation') },
        { instruction: 'Quad Stretch: 60 seconds each leg', duration: 120, animationUrl: getImageData('generic-animation') },
        { instruction: 'Full Body Stretch: 60 seconds', duration: 60, animationUrl: getImageData('generic-animation') },
    ],
  },
  {
    slug: 'low-back-recovery',
    title: 'Low Back Recovery',
    category: 'Rehabilitation',
    duration: 15,
    calories: 80,
    intensity: 'Beginner',
    equipment: ['Yoga Mat'],
    description: 'Gentle exercises to relieve lower back pain and improve mobility.',
    image: getImageData('rehab-workout'),
    steps: [
        { instruction: 'Pelvic Tilts: 2 sets of 15 reps', duration: 120, animationUrl: getImageData('generic-animation') },
        { instruction: 'Bird-Dog: 2 sets of 10 reps per side', duration: 180, animationUrl: getImageData('generic-animation') },
        { instruction: 'Glute Bridges: 2 sets of 15 reps', duration: 180, animationUrl: getImageData('generic-animation') },
        { instruction: 'Knee-to-Chest Stretch: 30 seconds per side', duration: 120, animationUrl: getImageData('generic-animation') },
        { instruction: 'Child\'s Pose: 60 seconds', duration: 60, animationUrl: getImageData('yoga-animation') },
    ],
  },
  {
    slug: 'resistance-band-burn',
    title: 'Resistance Band Burn',
    category: 'Strength',
    duration: 20,
    calories: 200,
    intensity: 'Intermediate',
    equipment: ['Resistance Bands'],
    description: 'A full-body workout using only resistance bands.',
    image: getImageData('resistance-workout'),
    steps: [
      { instruction: 'Banded Squats: 3 sets of 15 reps', duration: 180, animationUrl: getImageData('squat-animation') },
      { instruction: 'Banded Rows: 3 sets of 15 reps', duration: 180, animationUrl: getImageData('generic-animation') },
      { instruction: 'Bicep Curls: 3 sets of 15 reps per arm', duration: 180, animationUrl: getImageData('generic-animation') },
      { instruction: 'Tricep Extensions: 3 sets of 15 reps per arm', duration: 180, animationUrl: getImageData('generic-animation') },
      { instruction: 'Banded Glute Bridges: 3 sets of 20 reps', duration: 180, animationUrl: getImageData('generic-animation') },
    ],
  },
];

export const progressData: ProgressData[] = [
  { date: 'Mon', activity: 30, calories: 250 },
  { date: 'Tue', activity: 45, calories: 400 },
  { date: 'Wed', activity: 20, calories: 180 },
  { date: 'Thu', activity: 60, calories: 550 },
  { date: 'Fri', activity: 30, calories: 280 },
  { date: 'Sat', activity: 75, calories: 700 },
  { date: 'Sun', activity: 15, calories: 120 },
];

export const PIE_CHART_COLORS = {
  Strength: 'hsl(var(--chart-1))',
  Cardio: 'hsl(var(--chart-2))',
  Yoga: 'hsl(var(--chart-3))',
  HIIT: 'hsl(var(--chart-4))',
  Stretching: 'hsl(var(--chart-5))',
  Rehabilitation: 'hsl(var(--muted-foreground))',
  Other: 'hsl(var(--muted))'
}


export const achievements: Achievement[] = [
  {
    id: 'first-workout',
    title: 'First Step',
    description: 'Completed your first workout.',
    icon: Star,
  },
  {
    id: '7-day-streak',
    title: 'Week Warrior',
    description: 'Worked out 7 days in a row.',
    icon: Flame,
  },
  {
    id: '1000-calories',
    title: 'Calorie Crusher',
    description: 'Burned 1000 calories.',
    icon: Zap,
  },
  {
    id: '30-day-streak',
    title: 'Monthly Mover',
    description: 'Worked out for 30 days straight.',
    icon: Calendar,
  },
  {
    id: 'first-challenge',
    title: 'Challenger',
    description: 'Joined your first community challenge.',
    icon: Trophy,
  },
  {
    id: 'first-daily-challenge',
    title: 'Daily Contender',
    description: 'Completed your first daily challenge.',
    icon: CalendarCheck,
  },
  {
    id: 'morning-workout',
    title: 'Early Bird',
    description: 'Completed a workout before 8 AM.',
    icon: Activity,
  },
   {
    id: 'cardio-master',
    title: 'Cardio King',
    description: 'Completed 10 hours of cardio.',
    icon: HeartPulse,
  },
   {
    id: 'perfect-month',
    title: 'Perfect Month',
    description: 'Completed all planned workouts in a month.',
    icon: Award,
  },
  {
    id: 'push-up-pro',
    title: 'Push-up Pro',
    description: 'Completed 100 push-ups.',
    icon: Medal,
  },
  {
    id: 'top-contributor',
    title: 'Top Contributor',
    description: 'Made 10 posts in the community.',
    icon: MessageSquare,
  },
];
